[character]
error_symbol = "[\\(>_<\\) ✖](bold red)"

[time]
format = "[$time ]($style)"
style = "bold yellow"
time_format = "%R"
disabled = false

[git_status]
disabled = false

[memory_usage]
disabled = false
threshold = 90
format = "$symbol [${ram}]($style) "
style = "bold white"

[gcloud]
format = '[$symbol$project]($style) '
