[character]
error_symbol = "[\\(>_<\\) ✖](bold red)"

[directory]
truncation_length = 5

[hostname]
disabled = true

[time]
format = "[$time ]($style)"
style = "bold yellow"
time_format = "%R"
disabled = false

[git_status]
disabled = false

[memory_usage]
disabled = false
threshold = 90
format = "$symbol [${ram}]($style) "
style = "bold white"

[gcloud]
# TDOO: default なら表示消したい
format = '[$symbol$project]($style) as [$active](bold yellow) '

[username]
disabled = true

[docker_context]
disabled = true

[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold yellow"
format = "on [$output]($style) "
